# Generated by Django 5.1 on 2024-08-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plot_user_alter_seed_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Plot',
        ),
        migrations.DeleteModel(
            name='Seed',
        ),
    ]
